import {endpoint, entity, type QueryValue} from "./endpoints.shared";

export const centralEndpoints = {
  dashboard: {
    overview: "central/dashboard/overview",
    schoolsHealth: "central/dashboard/schools-health",
    systemHealth: "health",
  },
  schools: {
    list: (query: Record<string, QueryValue> = {}) => endpoint("central/schools", query),
    create: "central/schools",
    detail: (id: string) => `central/schools/${entity(id)}`,
    activate: (id: string) => `central/schools/${entity(id)}/activate`,
    deactivate: (id: string) => `central/schools/${entity(id)}/deactivate`,
    admin: (id: string) => `central/schools/${entity(id)}/admin`,
    createAdmin: (id: string) => `central/schools/${entity(id)}/create-admin`,
    resetAdminPassword: (id: string) => `central/schools/${entity(id)}/reset-admin-password`,
    users: {
      list: (schoolId: string, query: Record<string, QueryValue> = {}) => endpoint(`central/schools/${entity(schoolId)}/users`, query),
      create: (schoolId: string) => `central/schools/${entity(schoolId)}/users`,
      detail: (schoolId: string, userId: string) => `central/schools/${entity(schoolId)}/users/${entity(userId)}`,
      enable: (schoolId: string, userId: string) => `central/schools/${entity(schoolId)}/users/${entity(userId)}/enable`,
      disable: (schoolId: string, userId: string) => `central/schools/${entity(schoolId)}/users/${entity(userId)}/disable`,
      resetPassword: (schoolId: string, userId: string) => `central/schools/${entity(schoolId)}/users/${entity(userId)}/reset-password`,
      roles: (schoolId: string) => `central/schools/${entity(schoolId)}/roles`,
      permissions: (schoolId: string) => `central/schools/${entity(schoolId)}/permissions`,
      userRoles: (schoolId: string, userId: string) => `central/schools/${entity(schoolId)}/users/${entity(userId)}/roles`,
      assignRoles: (schoolId: string, userId: string) => `central/schools/${entity(schoolId)}/users/${entity(userId)}/roles/assign`,
      removeRoles: (schoolId: string, userId: string) => `central/schools/${entity(schoolId)}/users/${entity(userId)}/roles/remove`,
      effectivePermissions: (schoolId: string, userId: string) => `central/schools/${entity(schoolId)}/users/${entity(userId)}/effective-permissions`,
      grantPermissions: (schoolId: string, userId: string) => `central/schools/${entity(schoolId)}/users/${entity(userId)}/permissions/grant`,
      revokePermissions: (schoolId: string, userId: string) => `central/schools/${entity(schoolId)}/users/${entity(userId)}/permissions/revoke`,
      activity: (schoolId: string, userId: string, query: Record<string, QueryValue> = {}) => endpoint(`central/schools/${entity(schoolId)}/users/${entity(userId)}/activity`, query),
      audit: (schoolId: string, userId: string, query: Record<string, QueryValue> = {}) => endpoint(`central/schools/${entity(schoolId)}/users/${entity(userId)}/audit-log`, query),
    },
  },
  tickets: {
    list: (query: Record<string, QueryValue> = {}) => endpoint("central/tickets", query),
    detail: (id: string) => `central/tickets/${entity(id)}`,
    assign: (id: string) => `central/tickets/${entity(id)}/assign`,
    close: (id: string) => `central/tickets/${entity(id)}/close`,
  },
  audit: (query: Record<string, QueryValue> = {}) => endpoint("central/audit", query),
  policies: "central/policies",
} as const;
