import {endpoint, entity, type QueryValue} from "./endpoints.shared";

export const schoolEndpoints = {
  dashboard: {overview: "admin/reports/overview", kpis: "dashboard/kpis"},
  notifications: {
    list: (query: Record<string, QueryValue> = {}) => endpoint("notifications", query),
    detail: (id: string) => `notifications/${entity(id)}`,
    markRead: (id: string) => `notifications/${entity(id)}/read`,
  },
  users: {
    list: (query: Record<string, QueryValue> = {}) => endpoint("admin/users", query),
    detail: (id: string) => `admin/users/${entity(id)}`,
    create: "admin/users",
    update: (id: string) => `admin/users/${entity(id)}`,
    roles: "admin/roles",
    permissions: "admin/permissions",
    effective: (id: string) => `admin/users/${entity(id)}/effective-permissions`,
    disable: (id: string) => `admin/users/${entity(id)}/disable`,
    enable: (id: string) => `admin/users/${entity(id)}/enable`,
    reset: (id: string) => `admin/users/${entity(id)}/reset-password`,
    // The generic school-scoped contract replaces role membership atomically.
    // The admin route only adds roles and cannot express role removal safely.
    assignRoles: (id: string) => `users/${entity(id)}/roles`,
    grant: (id: string) => `admin/users/${entity(id)}/permissions/grant`,
    revoke: (id: string) => `admin/users/${entity(id)}/permissions/revoke`,
  },
  academics: {
    years: (query: Record<string, QueryValue> = {}) => endpoint("admin/academic-years", query),
    createYear: "admin/academic-years",
    updateYear: (id: string) => `admin/academic-years/${entity(id)}`,
    grades: (query: Record<string, QueryValue> = {}) => endpoint("grades", query),
    classrooms: (query: Record<string, QueryValue> = {}) => endpoint("classrooms", query),
    subjects: (query: Record<string, QueryValue> = {}) => endpoint("subjects", query),
  },
  attendance: {
    records: (query: Record<string, QueryValue> = {}) => endpoint("admin/attendance/records", query),
    manual: "admin/attendance/records/manual",
    update: (id: string) => `admin/attendance/records/${entity(id)}`,
    excuses: (query: Record<string, QueryValue> = {}) => endpoint("admin/excuses", query),
    approve: (id: string) => `admin/excuses/${entity(id)}/approve`,
    reject: (id: string) => `admin/excuses/${entity(id)}/reject`,
    qr: (query: Record<string, QueryValue> = {}) => endpoint("admin/qr/users", query),
    regenerateStudent: (id: string) => `admin/qr/students/${entity(id)}/regenerate`,
    regenerateTeacher: (id: string) => `admin/qr/teachers/${entity(id)}/regenerate`,
    regenerateStaff: (id: string) => `admin/qr/staff/${entity(id)}/regenerate`,
    revoke: (id: string) => `admin/qr/${entity(id)}/revoke`,
    rotateYear: "admin/qr/rotate-year",
  },
  documents: {
    overview: "admin/documents/overview",
    list: (query: Record<string, QueryValue> = {}) => endpoint("admin/documents", query),
    outgoing: (query: Record<string, QueryValue> = {}) => endpoint("admin/documents/outgoing", query),
    incoming: (query: Record<string, QueryValue> = {}) => endpoint("admin/documents/incoming", query),
    circulars: (query: Record<string, QueryValue> = {}) => endpoint("admin/documents/circulars", query),
    needsReply: (query: Record<string, QueryValue> = {}) => endpoint("admin/documents/needs-reply", query),
    create: "admin/documents",
    detail: (id: string) => `admin/documents/${entity(id)}`,
    update: (id: string) => `admin/documents/${entity(id)}`,
    delete: (id: string) => `admin/documents/${entity(id)}`,
    attachments: (id: string) => `admin/documents/${entity(id)}/attachments`,
    attachmentsList: (id: string) => `admin/documents/${entity(id)}/attachments`,
    download: (id: string, fileId: string) => `admin/documents/${entity(id)}/attachments/${entity(fileId)}/download`,
    preview: (id: string, fileId: string) => `admin/documents/${entity(id)}/attachments/${entity(fileId)}/preview`,
    markSent: (id: string) => `admin/documents/${entity(id)}/mark-sent`,
    markReceived: (id: string) => `admin/documents/${entity(id)}/mark-received`,
    reply: (id: string) => `admin/documents/${entity(id)}/create-reply`,
    link: (id: string) => `admin/documents/${entity(id)}/link`,
    archive: (id: string) => `admin/documents/${entity(id)}/archive`,
    activity: (id: string, query: Record<string, QueryValue> = {}) => endpoint(`admin/documents/${entity(id)}/activity`, query),
    categories: (query: Record<string, QueryValue> = {}) => endpoint("admin/document-categories", query),
    createCategory: "admin/document-categories",
    updateCategory: (id: string) => `admin/document-categories/${entity(id)}`,
    deleteCategory: (id: string) => `admin/document-categories/${entity(id)}`,
    parties: (query: Record<string, QueryValue> = {}) => endpoint("admin/correspondence-parties", query),
    createParty: "admin/correspondence-parties",
    updateParty: (id: string) => `admin/correspondence-parties/${entity(id)}`,
    deleteParty: (id: string) => `admin/correspondence-parties/${entity(id)}`,
  },
  reports: {
    attendance: (query: Record<string, QueryValue> = {}) => endpoint("admin/reports/attendance", query),
    points: (query: Record<string, QueryValue> = {}) => endpoint("admin/reports/points", query),
    behavior: (query: Record<string, QueryValue> = {}) => endpoint("admin/reports/behavior", query),
    atRisk: (query: Record<string, QueryValue> = {}) => endpoint("reports/at-risk", query),
    kpis: "reports/kpis",
  },
  tickets: {
    list: (query: Record<string, QueryValue> = {}) => endpoint("admin/tickets", query),
    assign: (id: string) => `admin/tickets/${entity(id)}/assign`,
    close: (id: string) => `admin/tickets/${entity(id)}/close`,
    escalate: (id: string) => `admin/tickets/${entity(id)}/escalate`,
  },
  settings: {detail: "admin/school/settings", features: "admin/school/features"},
} as const;
